### ISSUE TITLE
Improve HA password reset not available message

### ISSUE THREAD

**Issue by svh1985** [home-assistant/cli#204]
**Describe the bug**
When resetting a password I get `ERRO[0000] Unexpected server response`:
```
~ ha authentication reset --username "user" --password "pass"
ERRO[0000] Unexpected server response
```

The supervisor system log show’s:
```
20-02-29 15:10:12 WARNING (MainThread) [hassio.api.security] /auth/reset no role for a0d7b954_ssh
20-02-29 15:10:12 ERROR (MainThread) [hassio.api.security] Invalid token for access /auth/reset
```

**Debug info**
1. SSH Addon type:
https://github.com/hassio-addons/addon-ssh

2. Output of `ha --version`
```
➜  ~ ha info
arch: amd64
channel: stable
hassos: null
homeassistant: 0.106.2
hostname: HA
logging: info
machine: qemux86-64
supervisor: "201"
supported_arch:
- amd64
- i386
timezone: Europe/Amsterdam
```

3. Version of Home Assistant Core & the Home Assistant Supervisor
0.106.2 / 201

4. Output from executing the command with debug info.
```
➜  ~ ha hardware info
audio:
  "0":
    devices:
    - chan_id: "0"
      chan_type: digital audio playback
    - chan_id: "0"
      chan_type: digital audio capture
    - chan_id: "1"
      chan_type: digital audio playback
    - chan_id: "1"
      chan_type: digital audio capture
    - chan_id: "3"
      chan_type: digital audio playback
    - chan_id: "7"
      chan_type: digital audio playback
    - chan_id: "8"
      chan_type: digital audio playback
    - chan_id: "0"
      chan_type: hardware dependent
    - chan_id: "3"
      chan_type: hardware dependent
    name: HDA-Intel - HDA Intel PCH
    type: PCH
disk: []
gpio: []
input:
- HDA Intel PCH HDMI/DP,pcm=3
- HDA Intel PCH HDMI/DP,pcm=7
- Video Bus
- HDA Intel PCH Headphone
- Power Button
- Logitech MX Keys
- HDA Intel PCH Line
- PC Speaker
- Sleep Button
- HDA Intel PCH SPDIF In
- HDA Intel PCH HDMI/DP,pcm=8
serial:
- /dev/ttyS1
- /dev/ttyS3
- /dev/ttyS0
- /dev/ttyS2
```
