### ISSUE TITLE
deConz addon CLI install triggers: context deadline exceeded

### ISSUE THREAD

**Issue by xiki808** [home-assistant/cli#297]
## The problem
When installing the deConz addon from CLI: `addons install core_samba`, I get `Post "http://supervisor/addons/core_deconz/install": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`. The plugin eventually still installs, but this breaks automation scripts if there are other commands configuring this same addon. They will be executed before the addon is installed. 

## Environment
- Add-on with the issue: deConz
- Add-on release with the issue: 6.9.0
- Last working add-on release (if known): Ran the same script like a month ago and had no issues
- Operating environment (OS/Supervised): Home Assistant OS 5.13
- Core: core-2021.5.5
- Supervisor: supervisor-2021.04.3
- Home assistant run on a VM. Host OS: Proxmox 6.4

## Problem-relevant configuration
Nothing modified

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

## Additional information
Installing another addon, like Samba did not produce the same error.
